name: layover_app
description: A Flutter app for airline crew to explore layovers.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6



flutter:
  uses-material-design: true
